//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietthanhtoan
    {
        public int id { get; set; }
        public Nullable<int> idphieuthanhtoan { get; set; }
        public Nullable<int> idchitiet { get; set; }
        public string tenchiphi { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> gia { get; set; }
    
        public virtual phieuthanhtoan phieuthanhtoan { get; set; }
    }
}
