//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuthanhtoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuthanhtoan()
        {
            this.chitietthanhtoan = new HashSet<chitietthanhtoan>();
        }
    
        public int id { get; set; }
        public string tenphieu { get; set; }
        public Nullable<int> idloaiphieu { get; set; }
        public Nullable<int> iddoandulich { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietthanhtoan> chitietthanhtoan { get; set; }
        public virtual doandulich doandulich { get; set; }
        public virtual loaiphieu loaiphieu { get; set; }
    }
}
