//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class diadiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diadiem()
        {
            this.chitietdiemthamquan = new HashSet<chitietdiemthamquan>();
        }
    
        public int id { get; set; }
        public string tendiadiem { get; set; }
        public Nullable<int> idtt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdiemthamquan> chitietdiemthamquan { get; set; }
        public virtual tinhthanh tinhthanh { get; set; }
    }
}
