//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class giatour
    {
        public int id { get; set; }
        public Nullable<int> idtour { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
    
        public virtual tour tour { get; set; }
    }
}
