//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class phancong
    {
        public int id { get; set; }
        public Nullable<int> idnhanvien { get; set; }
        public Nullable<int> idnhiemvu { get; set; }
        public Nullable<int> iddoandulich { get; set; }
    
        public virtual doandulich doandulich { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        public virtual nhiemvu nhiemvu { get; set; }
    }
}
